### ISSUE TITLE
Redundant files and late modification

### ISSUE THREAD

**Issue by ugurdogrusoz** [karakahya/CS319-Group24#1]
You have 2 reports named analysis report (one under a directory). If you plan to put your documents under that directory then please delete the one in the root. I assume both files have the same content (one is created past due date)?
Let me know when you get rid of this problem.

**Comment by canbayraktar1** [comment]
Both files have the same content. After the deadline, we decided to create a reports folder and we decided to keep the one in the root in case a problem like this occurs. I can delete whichever you prefer.

**Comment by ugurdogrusoz** [comment]
Since you would like to have a separate folder for reports, get rid of the one in the root I suppose. Thanks

**Comment by karakahya** [comment]
The file in the root is deleted. It was there to show that we have completed the report before deadline since the folder created after the deadline.
Thanks.

**Comment by ugurdogrusoz** [comment]
@karakahya Thanks. But normally you should not close an issue as the person doing that tax / fixing that issue but assign it back to the creator to verify and close it!

**Comment by karakahya** [comment]
Oh sorry about that, you mentioned this before in class that is right.
Sorry for inconvenience.
Now reopened the issue and assigned it back.
